// Language strings for Easy Bitmap Maker
const strings = {
  en: {
    title: "🖼️ Easy Bitmap Maker 🖼️",
    widthLabel: "Width:",
    heightLabel: "Height:",
    penSizeLabel: "Pen Size:",
    outputFormatLabel: "Output Format:",
    langSwitch: "🇺🇸 English",
    modeFill: "🖌️ Fill",
    modeErase: "🧹 Erase",
    helpButton: "❓ Help",
    invertColors: "🔄 Invert Colors",
    importBitmap: "📥 Import Bitmap",
    clearGrid: "🗑️ Clear Grid",
    github: "🐙 GitHub",
    cppCodeTitle: "📄 Generated C++ Code",
    copyCode: "📋 Copy Code",
    starGithub: "⭐ If you like this project, please <a href=\"https://github.com/fram446742/easy-bitmap.github.io\" target=\"_blank\">star it on GitHub</a>! Also checkout original project: <a href=\"https://github.com/rokokol/easy-bitmap.github.io\" target=\"_blank\">Original Project</a>",
    rotate90: "↩️ Rotate 90°",
    flipHorizontal: "↔️ Flip Horizontal",
    flipVertical: "↕️ Flip Vertical",
    helpIntro: "Welcome to the Easy Bitmap Maker! Here's how to use the tool:",
    helpFillMode: "🖌️ <strong>Fill Mode:</strong> LMB draws pixels, RMB erases pixels",
    helpEraseMode: "🧹 <strong>Erase Mode:</strong> LMB erases pixels, RMB draws pixels",
    helpPenSize: "🎨 <strong>Pen Size:</strong> Adjust the pen size using the slider",
    helpImportBitmap: "📥 <strong>Import Bitmap:</strong> Import from C++ code or Arduino binary format (B00000000). The size must match the current grid dimensions.",
    helpGenerateCode: "💾 <strong>Generate C++ Code:</strong> View the C++ array in selected format",
    helpCopyCode: "📋 <strong>Copy Code:</strong> Copy the generated code",
    helpInvertColors: "🔄 <strong>Invert Colors:</strong> Invert all pixels",
    helpClearGrid: "🗑️ <strong>Clear Grid:</strong> Clear all pixels",
    helpHotkeys: '🔑 <strong>Hotkeys:</strong> <strong>{fill}</strong> for Fill, <strong>{erase}</strong> for Erase',
    helpRotate: "↩️ <strong>Rotate 90°:</strong> Rotate the bitmap by 90 degrees clockwise",
    helpFlipH: "↔️ <strong>Flip Horizontal:</strong> Flip horizontally",
    helpFlipV: "↕️ <strong>Flip Vertical:</strong> Flip vertically",
    helpLanguage: "🌐 <strong>Language:</strong> Toggle between languages",
    helpSupport: "⭐ <strong>Support:</strong> If you like this project, star it on GitHub",
    helpOutro: "Happy creating!",
    importTitle: "📥 Import Bitmap",
    importInstr: "Paste your C++ bitmap code, Arduino binary format, or array content below:",
    copySuccessTitle: "✅ Success",
    copySuccessText: "Code copied to clipboard!",
    error: "Error",
    enterBitmapCode: "Please enter the bitmap code.",
    sizeMismatch: "Bitmap size mismatch. Expected {expected} bits, got {got}.",
    success: "Success",
    bitmapImported: "Bitmap imported successfully!",
    hotkeyFill: "D",
    hotkeyErase: "E"
  },
  ru: {
    title: "🖼️ Easy Bitmap Maker 🖼️",
    widthLabel: "Ширина:",
    heightLabel: "Высота:",
    penSizeLabel: "Размер пера:",
    outputFormatLabel: "Формат вывода:",
    langSwitch: "🇷🇺 Русский",
    modeFill: "🖌️ Рисование",
    modeErase: "🧹 Стирание",
    helpButton: "❓ Справка",
    invertColors: "🔄 Инвертировать",
    importBitmap: "📥 Импортировать Bitmap",
    clearGrid: "🗑️ Очистить",
    github: "🐙 Гитхаб",
    cppCodeTitle: "📄 Сгенерированный C++ код",
    copyCode: "📋 Копировать код",
    starGithub: "⭐ Если вам понравился проект, пожалуйста, <a href=\"https://github.com/fram446742/easy-bitmap.github.io\" target=\"_blank\">поставьте звёздочку на GitHub</a>! Также ознакомьтесь с оригинальным проектом: <a href=\"https://github.com/rokokol/easy-bitmap.github.io\" target=\"_blank\">Оригинальный проект</a>",
    rotate90: "↩️ Повернуть 90°",
    flipHorizontal: "↔️ Отразить по горизонтали",
    flipVertical: "↕️ Отразить по вертикали",
    helpIntro: "Добро пожаловать в Easy Bitmap Maker! Вот как использовать инструмент:",
    helpFillMode: "🖌️ <strong>Рисование:</strong> ЛКМ рисует, ПКМ стирает",
    helpEraseMode: "🧹 <strong>Стирание:</strong> ЛКМ стирает, ПКМ рисует",
    helpPenSize: "🎨 <strong>Размер пера:</strong> Регулируйте ползунком",
    helpImportBitmap: "📥 <strong>Импорт битмапа:</strong> Импорт из C++ кода или формата Arduino binary (B00000000). Размер должен соответствовать текущим размерам сетки.",
    helpGenerateCode: "💾 <strong>Сгенерировать C++ код:</strong> Посмотреть массив C++ в выбранном формате",
    helpCopyCode: "📋 <strong>Копировать код:</strong> Скопировать сгенерированный код",
    helpInvertColors: "🔄 <strong>Инвертировать:</strong> Инвертировать все пиксели",
    helpClearGrid: "🗑️ <strong>Очистить:</strong> Очистить все пиксели",
    helpHotkeys: '🔑 <strong>Горячие клавиши:</strong> <strong>{fill}</strong> для рисования, <strong>{erase}</strong> для стирания',
    helpRotate: "↩️ <strong>Повернуть 90°:</strong> Повернуть изображение на 90°",
    helpFlipH: "↔️ <strong>Отразить по горизонтали:</strong> Отразить изображение",
    helpFlipV: "↕️ <strong>Отразить по вертикали:</strong> Отразить изображение",
    helpLanguage: "🌐 <strong>Язык:</strong> Переключение между языками",
    helpSupport: "⭐ <strong>Поддержка:</strong> Если вам нравится проект, поставьте звёздочку на GitHub",
    helpOutro: "Приятного творчества!",
    importTitle: "📥 Импортировать Bitmap",
    importInstr: "Вставьте ваш C++ код битмапа, формат Arduino binary или содержимое массива ниже:",
    copySuccessTitle: "✅ Успех",
    copySuccessText: "Код скопирован!",
    error: "Ошибка",
    enterBitmapCode: "Пожалуйста, введите код битмапа.",
    sizeMismatch: "Несоответствие размера битмапа. Ожидалось {expected} бит, получено {got}.",
    success: "Успех",
    bitmapImported: "Битмап успешно импортирован!",
    hotkeyFill: "В",
    hotkeyErase: "T"
  },
  es: {
    title: "🖼️ Easy Bitmap Maker 🖼️",
    widthLabel: "Ancho:",
    heightLabel: "Altura:",
    penSizeLabel: "Tamaño del lápiz:",
    outputFormatLabel: "Formato de salida:",
    langSwitch: "🇪🇸 Español",
    modeFill: "🖌️ Rellenar",
    modeErase: "🧹 Borrar",
    helpButton: "❓ Ayuda",
    invertColors: "🔄 Invertir colores",
    importBitmap: "📥 Importar Bitmap",
    clearGrid: "🗑️ Limpiar cuadrícula",
    github: "🐙 GitHub",
    cppCodeTitle: "📄 Código C++ generado",
    copyCode: "📋 Copiar código",
    starGithub: "⭐ Si te gusta este proyecto, por favor <a href=\"https://github.com/fram446742/easy-bitmap.github.io\" target=\"_blank\">estrellítalo en GitHub</a>! También échale un vistazo al proyecto original: <a href=\"https://github.com/rokokol/easy-bitmap.github.io\" target=\"_blank\">Proyecto Original</a>",
    rotate90: "↩️ Rotar 90°",
    flipHorizontal: "↔️ Voltear horizontal",
    flipVertical: "↕️ Voltear vertical",
    helpIntro: "¡Bienvenido a Easy Bitmap Maker! Aquí está cómo usar la herramienta:",
    helpFillMode: "🖌️ <strong>Modo rellenar:</strong> Clic izquierdo dibuja píxeles, clic derecho borra píxeles",
    helpEraseMode: "🧹 <strong>Modo borrar:</strong> Clic izquierdo borra píxeles, clic derecho dibuja píxeles",
    helpPenSize: "🎨 <strong>Tamaño del lápiz:</strong> Ajusta el tamaño del lápiz con el deslizador",
    helpImportBitmap: "📥 <strong>Importar Bitmap:</strong> Importa desde código C++ o formato binario Arduino (B00000000). El tamaño debe coincidir con las dimensiones actuales de la cuadrícula.",
    helpGenerateCode: "💾 <strong>Generar código C++:</strong> Ver el arreglo C++ en formato seleccionado",
    helpCopyCode: "📋 <strong>Copiar código:</strong> Copiar el código generado",
    helpInvertColors: "🔄 <strong>Invertir colores:</strong> Invertir todos los píxeles",
    helpClearGrid: "🗑️ <strong>Limpiar cuadrícula:</strong> Limpiar todos los píxeles",
    helpHotkeys: '🔑 <strong>Atajos:</strong> <strong>{fill}</strong> para rellenar, <strong>{erase}</strong> para borrar',
    helpRotate: "↩️ <strong>Rotar 90°:</strong> Rotar el bitmap 90 grados en sentido horario",
    helpFlipH: "↔️ <strong>Voltear horizontal:</strong> Voltear horizontalmente",
    helpFlipV: "↕️ <strong>Voltear vertical:</strong> Voltear verticalmente",
    helpLanguage: "🌐 <strong>Idioma:</strong> Cambiar entre idiomas",
    helpSupport: "⭐ <strong>Soporte:</strong> Si te gusta el proyecto, estrellítalo en GitHub",
    helpOutro: "¡Feliz creación!",
    importTitle: "📥 Importar Bitmap",
    importInstr: "Pega tu código de bitmap C++, formato binario Arduino o contenido del arreglo abajo:",
    copySuccessTitle: "✅ Éxito",
    copySuccessText: "¡Código copiado al portapapeles!",
    error: "Error",
    enterBitmapCode: "Por favor ingresa el código del bitmap.",
    sizeMismatch: "Desajuste de tamaño del bitmap. Esperado {expected} bits, obtenido {got}.",
    success: "Éxito",
    bitmapImported: "¡Bitmap importado exitosamente!",
    hotkeyFill: "D",
    hotkeyErase: "E"
  },
  fr: {
    title: "🖼️ Easy Bitmap Maker 🖼️",
    widthLabel: "Largeur:",
    heightLabel: "Hauteur:",
    penSizeLabel: "Taille du pinceau:",
    outputFormatLabel: "Format de sortie:",
    langSwitch: "🇫🇷 Français",
    modeFill: "🖌️ Remplir",
    modeErase: "🧹 Effacer",
    helpButton: "❓ Aide",
    invertColors: "🔄 Inverser les couleurs",
    importBitmap: "📥 Importer Bitmap",
    clearGrid: "🗑️ Effacer la grille",
    github: "🐙 GitHub",
    cppCodeTitle: "📄 Code C++ généré",
    copyCode: "📋 Copier le code",
    starGithub: "⭐ Si vous aimez ce projet, veuillez <a href=\"https://github.com/fram446742/easy-bitmap.github.io\" target=\"_blank\">le mettre en favori sur GitHub</a>! Consultez également le projet original : <a href=\"https://github.com/rokokol/easy-bitmap.github.io\" target=\"_blank\">Projet Original</a>",
    rotate90: "↩️ Tourner 90°",
    flipHorizontal: "↔️ Retourner horizontalement",
    flipVertical: "↕️ Retourner verticalement",
    helpIntro: "Bienvenue dans Easy Bitmap Maker ! Voici comment utiliser l'outil :",
    helpFillMode: "🖌️ <strong>Mode remplissage :</strong> Clic gauche dessine les pixels, clic droit efface les pixels",
    helpEraseMode: "🧹 <strong>Mode effacement :</strong> Clic gauche efface les pixels, clic droit dessine les pixels",
    helpPenSize: "🎨 <strong>Taille du pinceau :</strong> Ajustez la taille du pinceau avec le curseur",
    helpImportBitmap: "📥 <strong>Importer Bitmap :</strong> Importer depuis le code C++ ou le format binaire Arduino (B00000000). La taille doit correspondre aux dimensions actuelles de la grille.",
    helpGenerateCode: "💾 <strong>Générer le code C++ :</strong> Voir le tableau C++ dans le format sélectionné",
    helpCopyCode: "📋 <strong>Copier le code :</strong> Copier le code généré",
    helpInvertColors: "🔄 <strong>Inverser les couleurs :</strong> Inverser tous les pixels",
    helpClearGrid: "🗑️ <strong>Effacer la grille :</strong> Effacer tous les pixels",
    helpHotkeys: '🔑 <strong>Raccourcis :</strong> <strong>{fill}</strong> pour remplir, <strong>{erase}</strong> pour effacer',
    helpRotate: "↩️ <strong>Tourner 90° :</strong> Tourner le bitmap de 90 degrés dans le sens horaire",
    helpFlipH: "↔️ <strong>Retourner horizontalement :</strong> Retourner horizontalement",
    helpFlipV: "↕️ <strong>Retourner verticalement :</strong> Retourner verticalement",
    helpLanguage: "🌐 <strong>Langue :</strong> Basculer entre les langues",
    helpSupport: "⭐ <strong>Support :</strong> Si vous aimez le projet, mettez-le en favori sur GitHub",
    helpOutro: "Bonne création !",
    importTitle: "📥 Importer Bitmap",
    importInstr: "Collez votre code bitmap C++, format binaire Arduino ou contenu du tableau ci-dessous :",
    copySuccessTitle: "✅ Succès",
    copySuccessText: "Code copié dans le presse-papiers !",
    error: "Erreur",
    enterBitmapCode: "Veuillez saisir le code du bitmap.",
    sizeMismatch: "Incompatibilité de taille du bitmap. Attendu {expected} bits, obtenu {got}.",
    success: "Succès",
    bitmapImported: "Bitmap importé avec succès !",
    hotkeyFill: "D",
    hotkeyErase: "E"
  },
  de: {
    title: "🖼️ Easy Bitmap Maker 🖼️",
    widthLabel: "Breite:",
    heightLabel: "Höhe:",
    penSizeLabel: "Stiftgröße:",
    outputFormatLabel: "Ausgabeformat:",
    langSwitch: "🇩🇪 Deutsch",
    modeFill: "🖌️ Füllen",
    modeErase: "🧹 Löschen",
    helpButton: "❓ Hilfe",
    invertColors: "🔄 Farben invertieren",
    importBitmap: "📥 Bitmap importieren",
    clearGrid: "🗑️ Raster löschen",
    github: "🐙 GitHub",
    cppCodeTitle: "📄 Generierter C++ Code",
    copyCode: "📋 Code kopieren",
    starGithub: "⭐ Wenn dir dieses Projekt gefällt, bitte <a href=\"https://github.com/fram446742/easy-bitmap.github.io\" target=\"_blank\">sterne es auf GitHub</a>! Schau dir auch das Originalprojekt an: <a href=\"https://github.com/rokokol/easy-bitmap.github.io\" target=\"_blank\">Originalprojekt</a>",
    rotate90: "↩️ 90° drehen",
    flipHorizontal: "↔️ Horizontal spiegeln",
    flipVertical: "↕️ Vertikal spiegeln",
    helpIntro: "Willkommen bei Easy Bitmap Maker! Hier ist, wie du das Tool verwendest:",
    helpFillMode: "🖌️ <strong>Füllmodus:</strong> Linksklick zeichnet Pixel, Rechtsklick löscht Pixel",
    helpEraseMode: "🧹 <strong>Löschmodus:</strong> Linksklick löscht Pixel, Rechtsklick zeichnet Pixel",
    helpPenSize: "🎨 <strong>Stiftgröße:</strong> Passe die Stiftgröße mit dem Schieberegler an",
    helpImportBitmap: "📥 <strong>Bitmap importieren:</strong> Importiere aus C++ Code oder Arduino Binärformat (B00000000). Die Größe muss mit den aktuellen Rasterdimensionen übereinstimmen.",
    helpGenerateCode: "💾 <strong>C++ Code generieren:</strong> Das C++ Array im ausgewählten Format anzeigen",
    helpCopyCode: "📋 <strong>Code kopieren:</strong> Den generierten Code kopieren",
    helpInvertColors: "🔄 <strong>Farben invertieren:</strong> Alle Pixel invertieren",
    helpClearGrid: "🗑️ <strong>Raster löschen:</strong> Alle Pixel löschen",
    helpHotkeys: '🔑 <strong>Tastenkürzel:</strong> <strong>{fill}</strong> zum Füllen, <strong>{erase}</strong> zum Löschen',
    helpRotate: "↩️ <strong>90° drehen:</strong> Das Bitmap um 90 Grad im Uhrzeigersinn drehen",
    helpFlipH: "↔️ <strong>Horizontal spiegeln:</strong> Horizontal spiegeln",
    helpFlipV: "↕️ <strong>Vertikal spiegeln:</strong> Vertikal spiegeln",
    helpLanguage: "🌐 <strong>Sprache:</strong> Zwischen Sprachen wechseln",
    helpSupport: "⭐ <strong>Support:</strong> Wenn dir das Projekt gefällt, sterne es auf GitHub",
    helpOutro: "Viel Spaß beim Erstellen!",
    importTitle: "📥 Bitmap importieren",
    importInstr: "Füge deinen C++ Bitmap Code, Arduino Binärformat oder Array-Inhalt unten ein:",
    copySuccessTitle: "✅ Erfolg",
    copySuccessText: "Code in die Zwischenablage kopiert!",
    error: "Fehler",
    enterBitmapCode: "Bitte gib den Bitmap Code ein.",
    sizeMismatch: "Bitmap Größenunterschied. Erwartet {expected} Bits, erhalten {got}.",
    success: "Erfolg",
    bitmapImported: "Bitmap erfolgreich importiert!",
    hotkeyFill: "D",
    hotkeyErase: "E"
  }
};